name: Deploy Snapshot SonaType OSS

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-sonatype-oss:
    uses: sfuhrm/github_workflows/.github/workflows/maven-deploy-snapshot-sonatype-oss.yml@main
    with:
      environment: deploy
    secrets:
      sonatype_user: ${{ secrets.SONATYPE_USER }}
      sonatype_password: ${{ secrets.SONATYPE_PASSWORD }}

